# Generated by Django 4.1 on 2022-09-10 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=30)),
                ('country_dcode', models.CharField(max_length=30)),
                ('country_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'country_code',
            },
        ),
        migrations.RenameModel(
            old_name='PayState',
            new_name='DeliveryState',
        ),
        migrations.RenameField(
            model_name='deliverystate',
            old_name='status_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='wanteddata',
            old_name='pay_state',
            new_name='delivery_state',
        ),
        migrations.AlterModelTable(
            name='deliverystate',
            table='delivery_state',
        ),
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, null=True)),
                ('zipx', models.CharField(max_length=50)),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.countrycode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'delivery_info',
            },
        ),
        migrations.AddField(
            model_name='wanteddata',
            name='country_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.countrycode'),
            preserve_default=False,
        ),
    ]
