# Generated by Django 4.1 on 2022-09-12 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_countrycode_rename_paystate_deliverystate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wanteddata',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='wanteddata',
            name='country_code',
        ),
        migrations.AddField(
            model_name='wanteddata',
            name='pay_state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='country_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_codes', to='orders.countrycode'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
