# Generated by Django 4.1 on 2022-09-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_countrycode_rename_paystate_deliverystate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wanteddata',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='wanteddata',
            name='country_code',
        ),
        migrations.AddField(
            model_name='wanteddata',
            name='pay_state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
