# Generated by Django 4.1 on 2022-09-12 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_created_at_wanteddata_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrycode',
            old_name='country_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='countrycode',
            old_name='country_dcode',
            new_name='dcode',
        ),
        migrations.RenameField(
            model_name='countrycode',
            old_name='country_name',
            new_name='name',
        ),
    ]
