# Generated by Django 4.1 on 2022-09-12 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_country_code_countrycode_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryinfo',
            old_name='city_name',
            new_name='city',
        ),
    ]
