# Generated by Django 4.1 on 2022-09-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_use',
        ),
        migrations.AddField(
            model_name='couponissuelist',
            name='is_use',
            field=models.BooleanField(default=False),
        ),
    ]
