# Generated by Django 4.1 on 2022-09-13 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_remove_coupon_is_use_couponissuelist_is_use'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponissuelist',
            old_name='counpon',
            new_name='coupon',
        ),
    ]
