# Generated by Django 4.1 on 2022-09-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nickname', models.CharField(max_length=45, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=128)),
                ('is_superuser', models.IntegerField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.IntegerField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
    ]
